name: Deploy Workflow
# This workflow is triggered on pushes to the master branch.
on:
  push:
    branches:  
    - master

jobs:
  deploy:
    name: Deploy

    # Python should run the same on all OS but choosing Linux since that's what servers run on.
    runs-on: ubuntu-latest

    steps:
    # Check out code
    - uses: actions/checkout@v2
    # Set up Python
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    # Download project dependencies
    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # Update migrations
    - name: Database migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    # Run Django tests
    - name: Run Tests
      run: |
        python manage.py test
        
    # Deploy to Google App Engine
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - run: gcloud app deploy
